# Generated by Django 4.0.3 on 2022-04-02 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('league', models.CharField(choices=[('League 1', 'League 1'), ('Bundesliga', 'Bundesliga'), ('LaLiga', 'LaLiga'), ('English Premier League', 'English Premier League'), ('Seria A', 'Seria A')], max_length=155)),
                ('logo', models.ImageField(upload_to='../media/img/')),
                ('stadium', models.CharField(choices=[('Wembley', 'Wembley'), ('Old Trafford', 'Old Trafford'), ('Tottenham Hotspur Stadium', 'Tottenham Hotspur Stadium'), ('Emirates Stadium', 'Emirates Stadium'), ('Etihad Stadium', 'Etihad Stadium'), ('Anfield', 'Anfield'), ('Allianz Arena', 'Allianz Arena'), ('Estadio Santiago Bernabéu', 'Estadio Santiago Bernabéu')], max_length=155)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
