# Generated by Django 4.0.3 on 2022-04-15 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stadium', '0002_alter_stadium_author_alter_stadium_capacity_and_more'),
        ('club', '0002_alter_club_logo_alter_club_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.CharField(choices=[('League 1', 'League 1'), ('Bundesliga', 'Bundesliga'), ('LaLiga', 'LaLiga'), ('English Premier League', 'English Premier League'), ('Seria A', 'Seria A')], max_length=155, verbose_name='league_club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(upload_to='./media/img/', verbose_name='logo_club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=155, verbose_name='name_club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stadium_club', to='stadium.stadium'),
        ),
    ]
