# Generated by Django 4.0.3 on 2022-04-13 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_logo_alter_club_stadium'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballperson',
            name='age',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(75), django.core.validators.MinValueValidator(16)]),
        ),
        migrations.AddField(
            model_name='footballperson',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club'),
        ),
        migrations.AddField(
            model_name='footballperson',
            name='nation',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Albania', 'Albania'), ('France', 'France'), ('Portugal', 'Portugal'), ('Spain', 'Spain'), ('England', 'England'), ('Russia', 'Russia'), ('Belgium', 'Belgium'), ('Japan', 'Japan'), ('China', 'China'), ('Belarus', 'Belarus'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('United States', 'United States'), ('Turkey', 'Turkey'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Croatia', 'Croatia'), ('Poland', 'Poland')], default='1', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballperson',
            name='position',
            field=models.CharField(choices=[('GK', 'GoalKeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left WingBack'), ('RWB', 'Right WingBack'), ('CM', 'Centre Midfielder'), ('CDM', 'Centre Defensive Midfielder'), ('CAM', 'Centre Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('CF', 'Centre Forward'), ('LF', 'Left Forward'), ('RF', 'Right Forward'), ('ST', 'Striker')], default='1', max_length=3),
            preserve_default=False,
        ),
    ]
