# Generated by Django 4.0.3 on 2022-04-15 22:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0003_alter_club_author_alter_club_league_alter_club_logo_and_more'),
        ('person', '0002_footballperson_age_footballperson_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballperson',
            name='age',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(75), django.core.validators.MinValueValidator(16)], verbose_name='age_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_person', to=settings.AUTH_USER_MODEL, verbose_name='author_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_person', to='club.club'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='defending',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='defending_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='dribbling',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='dribbling_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='first_name',
            field=models.CharField(max_length=75, verbose_name='first_name_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='nation',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Albania', 'Albania'), ('France', 'France'), ('Portugal', 'Portugal'), ('Spain', 'Spain'), ('England', 'England'), ('Russia', 'Russia'), ('Belgium', 'Belgium'), ('Japan', 'Japan'), ('China', 'China'), ('Belarus', 'Belarus'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('United States', 'United States'), ('Turkey', 'Turkey'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Croatia', 'Croatia'), ('Poland', 'Poland')], max_length=55, verbose_name='nation_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='pace',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='pace_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='physics',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='physics_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='position',
            field=models.CharField(choices=[('GK', 'GoalKeeper'), ('CB', 'Centre Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('LWB', 'Left WingBack'), ('RWB', 'Right WingBack'), ('CM', 'Centre Midfielder'), ('CDM', 'Centre Defensive Midfielder'), ('CAM', 'Centre Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('CF', 'Centre Forward'), ('LF', 'Left Forward'), ('RF', 'Right Forward'), ('ST', 'Striker')], max_length=3, verbose_name='position_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='second_name',
            field=models.CharField(max_length=75, verbose_name='second_name_person'),
        ),
        migrations.AlterField(
            model_name='footballperson',
            name='shoots',
            field=models.PositiveSmallIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='shoots_person'),
        ),
    ]
